import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark select-none">
      <body
        className={"" + `${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <SidebarProvider>
          <AppSidebar />
            <SidebarTrigger className="sticky top-3 left-2 size-10" />
            <main className="flex-1 pl-8 pr-10">
              {children}
            </main>
          </SidebarProvider>
        </body>
    </html >
  );
}
